# .github/workflows/my-project.yml
name: MOIT

on:
  pull_request: 
    branches: [ main ]

jobs:
  build:
    name: test action
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Tuist
      run: curl -Ls https://install.tuist.io | bash
    - name: Fetch Swift Packages
      run: tuist fetch
    - name: Generate Project
      run: tuist generate
    - name: Build and Test
      run:  xcodebuild test -workspace MOIT.xcworkspace -scheme MOIT-Workspace -destination 'platform=iOS Simulator,name=iPhone 13 Pro,OS=latest' build test
