# .github/workflows/my-project.yml
name: MOIT

on:
  pull_request: 
    branches: [ develop ]

jobs:
  build:
    name: test action
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Tuist
      run: curl -Ls https://install.tuist.io | bash
    - name: Access Available
      run: chmod +x Scripts/setup.sh
    - name: Install Setup Script
      run: ./Scripts/setup.sh
    - name: Fetch Swift Packages
      run: moit fetch
    - name: Build and Test
      run:  tuist test MOIT-Workspace
